#!/usr/bin/env python

import argparse
from importlib import util as ilu
import subprocess


def main():
    p = argparse.ArgumentParser(description="Go to path for this python module")
    p.add_argument("module", help="The name of the module (what you would import")
    args = p.parse_args()

    path = '/'.join(ilu.find_spec(args.module).origin.split('/')[0:-1])
    print(path)
    subprocess.run(['vim', path])


if __name__ == '__main__':
    main()
